### ISSUE TITLE
同类型弃坑作品

### ISSUE THREAD

**Issue by zhuzi-z** [Chnja/zuoxuewen#1]
同学你好，我手上有一个不再维护的作品，完成度还可以，不知道你有没有兴趣接手。项目地址：[吾学](https://github.com/zhuzi-z/wuxue-public)（因为涉及的内容很多，所以未公开全部源码）

**Comment by Chnja** [comment]
主要我不会JAVA😔

**Comment by zhuzi-z** [comment]
好的👌🏻。其实我一开始也有做跨端的想法，但后面放弃了。如果你需要完整的源码，我也可以发你一份。
